# Generated by Django 5.0.6 on 2025-06-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('horarios', models.JSONField()),
                ('hobbies', models.JSONField(default=list)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
